---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data(rest_inspec)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plotly boxplot: Number of Restaurants by Borough of NYC

```{r}
rest_inspec|>
  filter(boro != "Missing")|>
  count(boro) |>
  mutate(boro = fct_reorder(boro, n)) |>
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis") |>
  layout((title = "Number of Restaurants by Borough of NYC"),
          xaxis = list(title = "Borough"),
          yaxis = list(title = "Number of Restaurants"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot: Average Score of Restaurants in Manhattan by Cuisine Type

```{r}
rest_inspec |>
  drop_na() |>
  filter(boro == "MANHATTAN",
         cuisine_description %in% c("American", "Mexican", "Italian", "Chinese", "Japanese", "Korean"))|>
  plot_ly(x = ~cuisine_description, y = ~score,color = ~cuisine_description, type = "box",colors = "viridis") |>
 layout((title = "Average Score of Restaurants in Manhattan by Cuisine Type"),
          xaxis = list(title = "Cuisine Type"),
          yaxis = list(title = "Inspection Score"))
```
  
### Scatter Plot

```{r}
rest_inspec |>
  drop_na() |>
  filter(boro == "MANHATTAN",
  grade %in% c("A", "B", "C"),
  cuisine_description %in% c("American", "Mexican", "Italian", "Chinese", "Japanese", "Korean")) |>
  mutate(text_label = str_c("Restaurant: ", dba, "\nGrade: ", grade)) |> 
  plot_ly(x = ~street, y = ~score, type = "scatter", mode = "markers", color = ~score,   text = ~text_label, colors = "viridis", alpha = 0.5)
```
